rvm:
  - 2.5.1
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
  - bundle exec rspec
before_script:
  - psql -c 'create database easy-rental_test' -U postgres
  